### ISSUE TITLE
Show pyapi version

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon-pyapi#7]
Show  pyapi version.
Both by (1) directly invoking the program; and (2) a method with which the clixon controller can fetch the version.
Proposal: -V command-line option show version and quits (same as clixon).

Reference: This is how versions are shown in the controller, but lacks pyapi version:
```
# op show version
Controller: 	0.3.0.PRE
Clixon: 	6.6.0.PRE
CLIgen: 	6.6.0.PRE

```
See also: https://github.com/clicon/clixon-controller/issues/101

**Comment by YotaYota** [comment]
I can fix this. I suggest that we merge https://github.com/clicon/clixon-pyapi/pull/6 first since it changes the usage from getops to argsparse in order to parse CLI arguments.

I got something in the pipe for this

**Comment by krihal** [comment]
Added.
